name: doctors_appointments
description: Doctors Appointments

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.8+28

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # GET
  get: 4.6.5
  get_storage: 2.1.1
  # DIO
  dio: 4.0.6
  dio_http_cache: 0.3.0
  # FONT
  google_fonts: 4.0.4
  #IMAGES, SLIDERS, LAYOUTS
  cached_network_image: 3.3.0
  carousel_slider: 4.2.1
  flutter_svg: ^2.0.7
  flutter_staggered_grid_view: 0.6.2
  image_picker: 0.8.7+5
  cupertino_icons: any
  shimmer: 3.0.0
  intl_phone_field: 3.1.0
  date_picker_timeline: 1.2.5
  # WEB
  webview_flutter: 4.2.1
  flutter_html: 3.0.0-alpha.2
  url_launcher: 6.1.11
  path_provider_ios: 2.0.11
  #JITSI MEET
  jitsi_meet:
    git:
      url: https://github.com/Eng-NUREDDIN/jitsi_meet.git
      path: jitsi_meet/
      ref: master
  # FIREBASE
  firebase_messaging: 14.6.2
  cloud_firestore: 4.8.0
  firebase_auth: 4.6.2
  firebase_core: 2.13.1
  firebase_storage: 11.2.2
  # GOOGLE MAPS
  geolocator: 9.0.2
  google_maps_flutter: 2.2.8
  google_maps_flutter_web: 0.5.0
  map_launcher: 2.5.0+1
  google_maps_place_picker_mb: 3.0.2
  flutter_localization: ^0.1.12
  introduction_screen: ^3.1.0
  lottie: ^2.3.2
  flutter_easyloading: ^3.0.5
  firebase_database: ^10.2.2



  flutter:
    sdk: flutter
#  flutter_localizations:
#    sdk: flutter
#  collection: ^1.15.0-nullsafety.4

dependency_overrides:
  meta: ^1.9.0
  intl: ^0.17.0

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  flutter_launcher_icons: 0.9.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - config/
    - assets/img/
    - assets/icon/
    - assets/animation/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
